// Definition of all the object assets and some attributes for each
export const OBJECT_ASSETS = [
  // {
  //   name: "Beyblade",
  //   file: "9584138/point_cloud.ply",
  //   scale: 0.5,
  //   shadowSize: 1.0,
  //   caption: "A blue and orange toy sphere with a spinning top and lid, resembling a beyblade and wheel shape.",
  // },
  {
    name: "Fridge",
    file: "9585727/point_cloud.ply",
    scale: 0.5,
    shadowSize: 1.0,
    caption: "a small white refrigerator.",
  },
  {
    name: "Jacket",
    file: "9585750/point_cloud.ply",
    scale: 0.5,
    shadowSize: 1.0,
    caption: "A denim jacket with graffiti and writing on it.",
  },
  // {
  //   name: "Small Plane",
  //   file: "9585791/point_cloud.ply",
  //   scale: 0.5,
  //   shadowSize: 1.0,
  //   caption: "a small plane flying.",
  // },
  {
    name: "Cat Mask",
    file: "9585798/point_cloud.ply",
    scale: 0.5,
    shadowSize: 1.0,
    caption: "White cat mask with red and yellow designs, inspired by Japanese style.",
  },
  // {
  //   name: "Wooden Stick",
  //   file: "9586352/point_cloud.ply",
  //   scale: 0.5,
  //   shadowSize: 1.0,
  //   caption: "a wooden stick",
  // },
  // {
  //   name: "Female Character",
  //   file: "9586359/point_cloud.ply",
  //   scale: 0.5,
  //   shadowSize: 1.0,
  //   caption: "a female character with blue hair and leather pants in a black outfit.",
  // },
  // {
  //   name: "Metal Box",
  //   file: "9586426/point_cloud.ply",
  //   scale: 0.5,
  //   shadowSize: 1.0,
  //   caption: "a large metal box with a blue lid, resembling a gun magazine and an ice block.",
  // },
  // {
  //   name: "Wooden Blocks",
  //   file: "9586907/point_cloud.ply",
  //   scale: 0.5,
  //   shadowSize: 1.0,
  //   caption: "Wooden modular blocks with interlocking design and circular recesses, featuring a natural wood finish and a small brass-colored label.",
  // },
  {
    name: "Wooden Drum",
    file: "9586912/point_cloud.ply",
    scale: 0.5,
    shadowSize: 1.0,
    caption: "Stylized wooden barrel drum with a brown body, decorative blue bands, metal clasps, rope detailing, and a brown handle with a braided pattern.",
  },
  // {
  //   name: "Coca-Cola Can",
  //   file: "9586980/point_cloud.ply",
  //   scale: 0.5,
  //   shadowSize: 1.0,
  //   caption: "a Coca-Cola can",
  // },
  {
    name: "Space Station",
    file: "9587013/point_cloud.ply",
    scale: 0.5,
    shadowSize: 1.0,
    caption: "a futuristic, modern building resembling a space station.",
  },
  {
    name: "Toy Gun",
    file: "9587064/point_cloud.ply",
    scale: 0.5,
    shadowSize: 1.0,
    caption: "a toy gun with an orange handle and a light.",
  },
  {
    name: "Mannequin Head",
    file: "9587169/point_cloud.ply",
    scale: 0.5,
    shadowSize: 1.0,
    caption: "white mannequin head.",
  },
  {
    name: "Pom-Pom",
    file: "9587187/point_cloud.ply",
    scale: 0.5,
    shadowSize: 1.0,
    caption: "a lime green furry pom-pom.",
  },
  // {
  //   name: "Rabbit Character",
  //   file: "9587465/point_cloud.ply",
  //   scale: 0.5,
  //   shadowSize: 1.0,
  //   caption: "Stylized a character with rabbit-like features, wearing a green and white checkered outfit, sporting large expressive blue eyes and brown and white fur details.",
  // },
  // {
  //   name: "Cat Statue",
  //   file: "9587534/point_cloud.ply",
  //   scale: 0.5,
  //   shadowSize: 1.0,
  //   caption: "an Egyptian cat statue sitting on a block.",
  // },
  {
    name: "Fireman Helmet",
    file: "9588028/point_cloud.ply",
    scale: 0.5,
    shadowSize: 1.0,
    caption: "a white fireman's metal helmet with a light and wires attached to it.",
  },
  // {
  //   name: "Wooden Crate",
  //   file: "9588101/point_cloud.ply",
  //   scale: 0.5,
  //   shadowSize: 1.0,
  //   caption: "a wooden crate on a checkered floor.",
  // },
  // {
  //   name: "Tank",
  //   file: "9588580/point_cloud.ply",
  //   scale: 0.5,
  //   shadowSize: 1.0,
  //   caption: "a camouflaged, tan armored tank.",
  // },
];
export const OBJECTS_URL = "data/"; 